# -*- coding: utf-8 -*-
"""WordGen_IS_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nD9os0F3FM5x9EDosUmcvknv8f4e8zWI
"""

from google.colab import files
import numpy as np

"""# Word count"""

def countingWord(dataConcat):

    arrayOfAscii = []
    arrayOfNumber = ['1','2','3','4','5','6','7','8','9','0']
    chatSymbol = []
    countingLang = []

    for code in range(ord('a'), ord('z') + 1):
        arrayOfAscii.append(chr(code))

    for i in dataConcat:

        CountEng = 0
        CountTha = 0
        CountNum = 0
        CountSym = 0

        for j in i:
            if j.isalpha():
                j = j.lower()
                if j in arrayOfAscii:
                    CountEng += 1
                    # print(j, 'Eng')
                else:
                    CountTha += 1
                    # print(j, 'Tha')

            elif j in arrayOfNumber:
                CountNum += 1
                # print(j, "Num")
                
            else:
                CountSym += 1
                # print(j,'Sym')
        
        countingLang.append([CountEng, CountTha, CountNum, CountSym])

    return countingLang

new_columns_count = ['CEng', 'CTha', 'CNum', 'CSym']

name_gen = pd.read_csv('./is_project_name_gen.csv')
name_gen = name_gen.drop(columns=['word_raw'])
counting_char = countingWord(name_gen.word)

df_count_word = pd.DataFrame(data = counting_char, columns=new_columns_count)
df_data_gen_word = pd.concat([name_gen, df_count_word], axis=1)

df_data_gen_word.to_csv('BB.csv') 
files.download('BB.csv')

"""# Gen per word

"""

df = pd.read_csv('/content/TrainingData.csv')

standby_fea = []
feature_col = []

array_result = []

for i in df.word:
  try:
    for j in i:
      standby_fea.append(j)
  except:
    pass

gen_pd = pd.DataFrame(data=standby_fea, columns=['A'])
gen_pd = gen_pd.drop_duplicates(subset=['A'])
gen_pd = gen_pd.to_numpy()
gen_pd = gen_pd.flatten()

for i in gen_pd:
  feature_col.append(i)
 

for idx2,ii in enumerate(df.word):
  id_col = df.ID_column[idx2]
  if ii == 'Null':
    array_result.append([id_col,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                        0,0,0,0,0,0,0,0,0,0,0])
  else:
    a=0
    b=0
    c=0
    d=0
    e=0
    f=0
    g=0
    h=0
    i=0
    j=0
    k=0
    l=0
    m=0
    n=0
    o=0
    p=0
    q=0
    r=0
    s=0
    t=0
    u=0
    v=0
    w=0
    x=0
    y=0
    z=0
    a1=0
    b1=0
    c1=0
    d1=0
    e1=0
    f1=0
    g1=0
    h1=0
    i1=0
    j1=0
    k1=0
    l1=0
    m1=0
    n1=0
    o1=0
    p1=0
    q1=0
    r1=0
    s1=0
    t1=0
    u1=0
    v1=0
    w1=0
    x1=0
    y1=0
    z1=0
    a2=0
    b2=0
    c2=0
    d2=0
    e2=0
    f2=0
    g2=0
    h2=0
    i2=0
    j2=0
    k2=0
    l2=0
    m2=0
    n2=0
    o2=0
    p2=0
    q2=0
    r2=0
    s2=0
    t2=0
    u2=0
    v2=0
    w2=0
    x2=0
    y2=0
    z2=0
    a3=0
    b3=0
    c3=0
    d3=0
    e3=0
    f3=0
    g3=0
    h3=0
    i3=0
    j3=0
    k3=0
    l3=0
    m3=0
    n3=0
    o3=0
    p3=0
    q3=0
    r3=0
    s3=0
    t3=0
    u3=0
    v3=0
    w3=0
    x3=0
    y3=0
    z3=0
    a4=0
    b4=0
    c4=0
    d4=0
    e4=0
    f4=0
    g4=0
    h4=0
    i4=0
    j4=0
    k4=0
    l4=0
    m4=0
    n4=0
    o4=0
    p4=0
    q4=0
    r4=0
    s4=0
    t4=0
    u4=0
    v4=0
    w4=0
    x4=0
    y4=0
    z4=0
    a5=0
    b5=0
    c5=0
    d5=0
    e5=0
    f5=0
    g5=0
    h5=0
    i5=0
    j5=0
    k5=0
    l5=0
    m5=0
    n5=0
    o5=0
    p5=0
    q5=0
    r5=0
    s5=0
    t5=0
    u5=0
    v5=0
    w5=0
    x5=0
    y5=0
    z5=0
    a6=0
    b6=0
    c6=0
    d6=0
    e6=0
    f6=0
    g6=0
    h6=0
    i6=0
    j6=0
    k6=0
    # l6=0
 

    try:
      for jj in ii:
        ii = str(ii)
        if jj == feature_col[0]:
          a += 1
        elif jj == feature_col[1]:
          b += 1
        elif jj == feature_col[2]:
          c += 1
        elif jj == feature_col[3]:
          d += 1
        elif jj == feature_col[4]:
          e += 1
        elif jj == feature_col[5]:
          f += 1
        elif jj == feature_col[6]:
          g += 1
        elif jj == feature_col[7]:
          h += 1
        elif jj == feature_col[8]:
          i += 1
        elif jj == feature_col[9]:
          j += 1
        elif jj == feature_col[10]:
          k += 1
        elif jj == feature_col[11]:
          l += 1
        elif jj == feature_col[12]:
          m += 1
        elif jj == feature_col[13]:
          n += 1
        elif jj == feature_col[14]:
          o += 1
        elif jj == feature_col[15]:
          p += 1
        elif jj == feature_col[16]:
          q += 1
        elif jj == feature_col[17]:
          r += 1
        elif jj == feature_col[18]:
          s += 1
        elif jj == feature_col[19]:
          t += 1
        elif jj == feature_col[20]:
          u += 1
        elif jj == feature_col[21]:
          v += 1
        elif jj == feature_col[22]:
          w += 1
        elif jj == feature_col[23]:
          x += 1
        elif jj == feature_col[24]:
          y += 1
        elif jj == feature_col[25]:
          z += 1
        elif jj == feature_col[26]:
          a1 += 1
        elif jj == feature_col[27]:
          b1 += 1
        elif jj == feature_col[28]:
          c1 += 1
        elif jj == feature_col[29]:
          d1 += 1
        elif jj == feature_col[30]:
          e1 += 1
        elif jj == feature_col[31]:
          f1 += 1
        elif jj == feature_col[32]:
          g1 += 1
        elif jj == feature_col[33]:
          h1 += 1
        elif jj == feature_col[34]:
          i1 += 1
        elif jj == feature_col[35]:
          j1 += 1
        elif jj == feature_col[36]:
          k1 += 1
        elif jj == feature_col[37]:
          l1 += 1
        elif jj == feature_col[38]:
          m1 += 1
        elif jj == feature_col[39]:
          n1 += 1
        elif jj == feature_col[40]:
          o1 += 1
        elif jj == feature_col[41]:
          p1 += 1
        elif jj == feature_col[42]:
          q1 += 1
        elif jj == feature_col[43]:
          r1 += 1
        elif jj == feature_col[44]:
          s1 += 1
        elif jj == feature_col[45]:
          t1 += 1
        elif jj == feature_col[46]:
          u1 += 1
        elif jj == feature_col[47]:
          v1 += 1
        elif jj == feature_col[48]:
          w1 += 1
        elif jj == feature_col[49]:
          x1 += 1
        elif jj == feature_col[50]:
          y1 += 1
        elif jj == feature_col[51]:
          z1 += 1
        elif jj == feature_col[52]:
          a2 += 1
        elif jj == feature_col[53]:
          b2 += 1
        elif jj == feature_col[54]:
          c2 += 1
        elif jj == feature_col[55]:
          d2 += 1
        elif jj == feature_col[56]:
          e2 += 1
        elif jj == feature_col[57]:
          f2 += 1
        elif jj == feature_col[58]:
          g2 += 1
        elif jj == feature_col[59]:
          h2 += 1
        elif jj == feature_col[60]:
          i2 += 1
        elif jj == feature_col[61]:
          j2 += 1
        elif jj == feature_col[62]:
          k2 += 1
        elif jj == feature_col[63]:
          l2 += 1
        elif jj == feature_col[64]:
          m2 += 1
        elif jj == feature_col[65]:
          n2 += 1
        elif jj == feature_col[66]:
          o2 += 1
        elif jj == feature_col[67]:
          p2 += 1
        elif jj == feature_col[68]:
          q2 += 1
        elif jj == feature_col[69]:
          r2 += 1
        elif jj == feature_col[70]:
          s2 += 1
        elif jj == feature_col[71]:
          t2 += 1
        elif jj == feature_col[72]:
          u2 += 1
        elif jj == feature_col[73]:
          v2 += 1
        elif jj == feature_col[74]:
          w2 += 1
        elif jj == feature_col[75]:
          x2 += 1
        elif jj == feature_col[76]:
          y2 += 1
        elif jj == feature_col[77]:
          z2 += 1
        elif jj == feature_col[78]:
          a3 += 1
        elif jj == feature_col[79]:
          b3 += 1
        elif jj == feature_col[80]:
          c3 += 1
        elif jj == feature_col[81]:
          d3 += 1
        elif jj == feature_col[82]:
          e3 += 1
        elif jj == feature_col[83]:
          f3 += 1
        elif jj == feature_col[84]:
          g3 += 1
        elif jj == feature_col[85]:
          h3 += 1
        elif jj == feature_col[86]:
          i3 += 1
        elif jj == feature_col[87]:
          j3 += 1
        elif jj == feature_col[88]:
          k3 += 1
        elif jj == feature_col[89]:
          l3 += 1
        elif jj == feature_col[90]:
          m3 += 1
        elif jj == feature_col[91]:
          n3 += 1
        elif jj == feature_col[92]:
          o3 += 1
        elif jj == feature_col[93]:
          p3 += 1
        elif jj == feature_col[94]:
          q3 += 1
        elif jj == feature_col[95]:
          r3 += 1
        elif jj == feature_col[96]:
          s3 += 1
        elif jj == feature_col[97]:
          t3 += 1
        elif jj == feature_col[98]:
          u3 += 1
        elif jj == feature_col[99]:
          v3 += 1
        elif jj == feature_col[100]:
          w3 += 1
        elif jj == feature_col[101]:
          x3 += 1
        elif jj == feature_col[102]:
          y3 += 1
        elif jj == feature_col[103]:
          z3 += 1
        elif jj == feature_col[104]:
          a4 += 1
        elif jj == feature_col[105]:
          b4 += 1
        elif jj == feature_col[106]:
          c4 += 1
        elif jj == feature_col[107]:
          d4 += 1
        elif jj == feature_col[108]:
          e4 += 1
        elif jj == feature_col[109]:
          f4 += 1
        elif jj == feature_col[110]:
          g4 += 1
        elif jj == feature_col[111]:
          h4 += 1
        elif jj == feature_col[112]:
          i4 += 1
        elif jj == feature_col[113]:
          j4 += 1
        elif jj == feature_col[114]:
          k4 += 1
        elif jj == feature_col[115]:
          l4 += 1
        elif jj == feature_col[116]:
          m4 += 1
        elif jj == feature_col[117]:
          n4 += 1
        elif jj == feature_col[118]:
          o4 += 1
        elif jj == feature_col[119]:
          p4 += 1
        elif jj == feature_col[120]:
          q4 += 1
        elif jj == feature_col[121]:
          r4 += 1
        elif jj == feature_col[122]:
          s4 += 1
        elif jj == feature_col[123]:
          t4 += 1
        elif jj == feature_col[124]:
          u4 += 1
        elif jj == feature_col[125]:
          v4 += 1
        elif jj == feature_col[126]:
          w4 += 1
        elif jj == feature_col[127]:
          x4 += 1
        elif jj == feature_col[128]:
          y4 += 1
        elif jj == feature_col[129]:
          z4 += 1
        elif jj == feature_col[130]:
          a5 += 1
        elif jj == feature_col[131]:
          b5 += 1
        elif jj == feature_col[132]:
          c5 += 1
        elif jj == feature_col[133]:
          d5 += 1
        elif jj == feature_col[134]:
          e5 += 1
        elif jj == feature_col[135]:
          f5 += 1
        elif jj == feature_col[136]:
          g5 += 1
        elif jj == feature_col[137]:
          h5 += 1
        elif jj == feature_col[138]:
          i5 += 1
        elif jj == feature_col[139]:
          j5 += 1
        elif jj == feature_col[140]:
          k5 += 1
        elif jj == feature_col[141]:
          l5 += 1
        elif jj == feature_col[142]:
          m5 += 1
        elif jj == feature_col[143]:
          n5 += 1
        elif jj == feature_col[144]:
          o5 += 1
        elif jj == feature_col[145]:
          p5 += 1
        elif jj == feature_col[146]:
          q5 += 1
        elif jj == feature_col[147]:
          r5 += 1
        elif jj == feature_col[148]:
          s5 += 1
        elif jj == feature_col[149]:
          t5 += 1
        elif jj == feature_col[150]:
          u5 += 1
        elif jj == feature_col[151]:
          v5 += 1
        elif jj == feature_col[152]:
          w5 += 1
        elif jj == feature_col[153]:
          x5 += 1
        elif jj == feature_col[154]:
          y5 += 1
        elif jj == feature_col[155]:
          z5 += 1
        elif jj == feature_col[156]:
          a6 += 1
        elif jj == feature_col[157]:
          b6 += 1
        elif jj == feature_col[158]:
          c6 += 1
        elif jj == feature_col[159]:
          d6 += 1
        elif jj == feature_col[160]:
          e6 += 1
        elif jj == feature_col[161]:
          f6 += 1
        elif jj == feature_col[162]:
          g6 += 1
        elif jj == feature_col[163]:
          h6 += 1
        elif jj == feature_col[164]:
          i6 += 1
        elif jj == feature_col[165]:
          j6 += 1
        elif jj == feature_col[166]:
          k6 += 1
        # elif jj == feature_col[167]:
        #   l6 += 1
    except:
      pass

    array_result.append([id_col,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,
                        a1,b1,c1,d1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,u1,v1,w1,x1,y1,z1,
                        a2,b2,c2,d2,e2,f2,g2,h2,i2,j2,k2,l2,m2,n2,o2,p2,q2,r2,s2,t2,u2,v2,w2,x2,y2,z2,
                        a3,b3,c3,d3,e3,f3,g3,h3,i3,j3,k3,l3,m3,n3,o3,p3,q3,r3,s3,t3,u3,v3,w3,x3,y3,z3,
                        a4,b4,c4,d4,e4,f4,g4,h4,i4,j4,k4,l4,m4,n4,o4,p4,q4,r4,s4,t4,u4,v4,w4,x4,y4,z4,
                        a5,b5,c5,d5,e5,f5,g5,h5,i5,j5,k5,l5,m5,n5,o5,p5,q5,r5,s5,t5,u5,v5,w5,x5,y5,z5,
                        a6,b6,c6,d6,e6,f6,g6,h6,i6,j6,k6])

 
put_col_in = pd.DataFrame(data= array_result, columns=feature_col)

df_con = pd.concat([df,put_col_in], axis=1)
df_con.to_csv('Fullword_14112021.csv') 
files.download('Fullword_14112021.csv')